
on:
  workflow_dispatch:
  release:
    types:
      - created

env:
  plugin: dev.cazzar.streamdeck.vtubestudio.sdPlugin

jobs:
  binary:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build for windows
        run: dotnet publish -c Release --runtime win-x64 -o build

      - name: build for osx
        run: dotnet publish -c Release --runtime osx-x64 -o build

      - uses: actions/upload-artifact@v2
        with:
          name: binary-out
          path: build/

  property-inspector:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build property inspector
        run: |
          yarn install --frozen-lockfile
          yarn build
        working-directory: ./PropertyInspector

      - uses: actions/upload-artifact@v2
        with:
          name: property-inspector
          path: ./PropertyInspector/dist/

  bundle:
    runs-on: windows-latest
    needs:
      - binary
      - property-inspector
    steps:

      - uses: actions/download-artifact@v2
        with:
          name: binary-out
          path: ${{ env.plugin }}

      - uses: actions/download-artifact@v2
        with:
          name: property-inspector
          path: ${{ env.plugin }}/PropertyInspector

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ${{ env.plugin }}

      - name: download dist tool
        run: |
          Invoke-WebRequest "https://developer.elgato.com/documentation/stream-deck/distributiontool/DistributionToolWindows.zip" -OutFile DistributionTool.zip
          Expand-Archive DistributionTool.zip -DestinationPath .

      - name: make sdPlugin package
        run: ./DistributionTool.exe -b -i ${{ env.plugin }} -o .

  artifact:
    runs-on: windows-latest
    needs: bundle
    steps:
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.plugin }}
          path: ${{ env.plugin }}