
on:
  workflow_dispatch:
  release:
    types:
      - created

env:
  plugin: dev.cazzar.streamdeck.vtubestudio.sdPlugin

jobs:
  build-image:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build for windows
        run: dotnet publish -c Release --runtime win-x64 -o ${{ env.plugin }}

      - name: build for osx
        run: dotnet publish -c Release --runtime osx-x64 -o ${{ env.plugin }}

      - name: build property inspector
        run: |
          yarn install --frozen-lockfile
          yarn build
        working-directory: ./PropertyInspector

      - name: copy PI to output
        run: Copy-Item "./PropertyInspector/dist/*" -Destination "./${{ env.plugin }}/PropertyInspector" -Recurse

      - name: download dist tool
        run: |
          Invoke-WebRequest "https://developer.elgato.com/documentation/stream-deck/distributiontool/DistributionToolWindows.zip" -OutDir DistributionTool.zip
          Expand-Archive DistributionTool.zip -DestinationPath .

      - name: make sdPlugin package
        run: ./DistributionTool.exe -b -i ${{ env.plugin }} -o .


